// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTSZQYqQEwLyCyC4WI6spjgBGXgNcvmmk',
    appId: '1:1009995334395:android:c6b1c3233ac00dfa30a65e',
    messagingSenderId: '1009995334395',
    projectId: 'seen-cd6cf',
    storageBucket: 'seen-cd6cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWUh_RfWDS1L8AtI8DJ4A98uhykHoJ0w',
    appId: '1:1009995334395:ios:90d8d8e5edb5040a30a65e',
    messagingSenderId: '1009995334395',
    projectId: 'seen-cd6cf',
    storageBucket: 'seen-cd6cf.firebasestorage.app',
    androidClientId: '1009995334395-kj12e22k020j3sfpte1eq9rtmfe69jcf.apps.googleusercontent.com',
    iosClientId: '1009995334395-csnb3ks7v7esgddkpnuhoj9dhoa8pfnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.javaSevaAi',
  );
}
